# Generated by Django 2.2.3 on 2020-08-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewform',
            name='houseaddress',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='reviewform',
            name='lat',
            field=models.CharField(default=1, max_length=25),
        ),
        migrations.AddField(
            model_name='reviewform',
            name='lng',
            field=models.CharField(default=1, max_length=25),
        ),
    ]
