# Generated by Django 2.2.3 on 2020-08-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('lat', models.CharField(max_length=25)),
                ('lng', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.CharField(max_length=25),
        ),
    ]
