# Generated by Django 2.2.9 on 2020-08-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewform',
            name='floor',
            field=models.CharField(blank=True, choices=[('OUTSIDE', '지상'), ('SEMIINSIDE', '반지하'), ('INSIDE', '지하')], max_length=3, null=True),
        ),
    ]
