# Generated by Django 2.2.9 on 2020-08-08 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20200808_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewform',
            name='houseaddress',
        ),
        migrations.RemoveField(
            model_name='reviewform',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='reviewform',
            name='lng',
        ),
        migrations.AddField(
            model_name='reviewform',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='review.Place'),
            preserve_default=False,
        ),
    ]
