# Generated by Django 2.2.3 on 2020-08-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20200807_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='gu',
            field=models.CharField(default='1', max_length=25),
        ),
    ]
