# Generated by Django 2.2.3 on 2020-08-14 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_buylist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buylist',
        ),
    ]
