# Generated by Django 3.1.1 on 2020-09-29 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_seoullatlngmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gu', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='seoullatlngmark',
            name='name',
        ),
        migrations.AddField(
            model_name='seoullatlngmark',
            name='gu_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.gu'),
        ),
    ]
