# Generated by Django 2.2.9 on 2020-08-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_school_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='image',
        ),
    ]
