# Generated by Django 2.2.9 on 2020-08-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20200807_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
