# Generated by Django 2.2.3 on 2020-08-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20200810_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='gu',
            field=models.CharField(default=1, max_length=25),
        ),
    ]
