# Generated by Django 2.2.3 on 2020-08-14 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_reviewlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reviewlist',
        ),
    ]
