# Generated by Django 2.2.3 on 2020-08-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_reviewlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='buylist',
            field=models.CharField(default=list, max_length=10000, null=True),
        ),
    ]
