# Generated by Django 2.2.9 on 2020-08-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20200818_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='email_list',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
