# Generated by Django 2.2.9 on 2020-08-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20200818_1439'),
        ('community', '0003_auto_20200818_1412'),
    ]

    operations = [
    ]
