# Generated by Django 2.2.15 on 2020-08-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20200811_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='제목')),
            ],
        ),
    ]
