# Generated by Django 2.2.15 on 2020-08-11 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0005_all_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='all_post_photos')),
                ('title', models.CharField(max_length=64, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='수정 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 시간')),
                ('School', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.School')),
                ('all_community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.All_Community')),
                ('like_users', models.ManyToManyField(related_name='all_like_posts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
